name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 10 * * *"

jobs:
  stable:
    name: Deno Stable

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.4.6

      - name: Run tests
        run: deno test --unstable --allow-read --allow-write --allow-net src

  nightly:
    name: Deno Nightly

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: nightly

      - name: Run tests
        run: deno test --unstable --allow-read --allow-write --allow-net src
